version = 0.1
[default.deploy.parameters]
stack_name = "nest8"
resolve_s3 = true
s3_prefix = "nest8"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
